import { Injectable } from '@angular/core';
import { ItemsClass } from './Classes/ItemClass';
import { BehaviorSubject, Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class ItemsListService {

  constructor() { }
  ProductsList: ItemsClass[] = [
    {
      'Name': "Lays Chilli Chips",
      'Description': "Crunch into happiness with Red Lays — bold flavor, perfect crisp, and pure snacking joy!",
      'Price': 20,
      'AwailableQuantity': 34,
      'Img1': "images/LaysChips_P1_img1.jpeg",
      'Img2': "images/P1_img2.jpeg",
      'Img3': "images/P1_img3.jpeg",
      'Img4': "images/P1_img4.jpeg",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'CategoryId': 2,
      'ProductId': 1,
    },
    {
      'Name': "Amul Chocobar dark frost",
      'Description': "Indulge in creamy Amul Chocobar — rich chocolate outside, velvety ice cream inside!",
      'Price': 35,
      'AwailableQuantity': 23,
      'Img1': "images/AmulIceCream_P2_img1.jpeg",
      'Img2': "images/P2_img2.jpeg",
      'Img3': "images/P2_img3.jpeg",
      'Img4': "images/P2_img4.jpeg",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'CategoryId': 6,
      'ProductId': 2,
    },
    {
      'Name': "Coca Cola",
      'Description': "Open happiness with Coca-Cola — the classic, refreshing taste that never goes out of style!",
      'Price': 40,
      'AwailableQuantity': 83,
      'Img1': "images/CocaCola_P3_img1.jpeg",
      'Img2': "images/P3_img2.jpeg",
      'Img3': "images/P3_img3.jpeg",
      'Img4': "images/P3_img4.jpeg",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'CategoryId': 7,
      'ProductId': 3,
    },
    {
      'Name': "Marry Gold",
      'Description': "Start your day light and right with Marie Gold — crispy, wholesome goodness in every bite!",
      'Price': 10,
      'AwailableQuantity': 45,
      'Img1': "images/MarryGold_P4_img1.jpeg",
      'Img2': "images/MarryGold_P4_img1.jpeg",
      'Img3': "images/MarryGold_P4_img1.jpeg",
      'Img4': "images/MarryGold_P4_img1.jpeg",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'CategoryId': 2,
      'ProductId': 4,
    },
    {
      'Name': "Haldiram Aloo Bhujiya",
      'Description': "Spice up your snack time with Aloo Bhujia — crispy, tangy, and irresistibly crunchy",
      'Price': 349,
      'AwailableQuantity': 25,
      'Img1': "images/AlooBhujia_P5_img1.jpeg",
      'Img2': "images/P5_img2.jpeg",
      'Img3': "images/P5_img3.jpeg",
      'Img4': "images/P5_img4.jpeg",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'CategoryId': 2,
      'ProductId': 5,
    },
    {
      'Name': "Amul Butter",
      'Description': "Utterly Butterly Delicious Amul Butter — the creamy taste that makes everything better",
      'Price': 60,
      'AwailableQuantity': 63,
      'Img1': "images/AmulButter_P6_img1.jpeg",
      'Img2': "images/P6_img2.jpeg",
      'Img3': "images/P6_img3.jpeg",
      'Img4': "images/P6_img4.jpeg",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'CategoryId': 1,
      'ProductId': 6,
    },
    {
      'Name': "Amul Milk",
      'Description': "Amul Doodh — the taste of purity and the strength of good health in every glass",
      'Price': 35,
      'AwailableQuantity': 34,
      'Img1': "images/AmulDudh_P7_img1.jpeg",
      'Img2': "images/P7_img2.jpeg",
      'Img3': "images/P7_img3.jpeg",
      'Img4': "images/P7_img4.jpeg",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'CategoryId': 1,
      'ProductId': 7,

    },
    {
      'Name': "Fortune Refined",
      'Description': "Cook with care, cook with Fortune Refined — purity and taste for a healthier you",
      'Price': 155,
      'AwailableQuantity': 23,
      'Img1': "images/FortuneRefined_P8_img1.jpeg",
      'Img2': "images/P8_img2.jpeg",
      'Img3': "images/P8_img3.jpeg",
      'Img4': "images/P8_img4.jpeg",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'CategoryId': 2,
      'ProductId': 8,
    },
    {
      'Name': "Pedegree",
      'Description': "Healthy, happy tails with Pedigree — nutritious meals your dog will love every day",
      'Price': 2042,
      'AwailableQuantity': 83,
      'Img1': "images/Pedegree_P9_img1.jpeg",
      'Img2': "images/P9_img1.jpeg",
      'Img3': "images/P9_img1.jpeg",
      'Img4': "images/P9_img1.jpeg",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'CategoryId': 8,
      'ProductId': 9,
    },
    {
      'Name': "Melody",
      'Description': "Melody — the chocolatey toffee that makes you wonder, ‘Why so chocolaty?",
      'Price': 48,
      'AwailableQuantity': 45,
      'Img1': "images/Melody_P10_img1.jpeg",
      'Img2': "images/P10_img1.jpeg",
      'Img3': "images/P10_img1.jpeg",
      'Img4': "images/P10_img1.jpeg",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'CategoryId': 10,
      'ProductId': 10,
    },
    {
      'Name': "Raw Meat",
      'Description': "Fresh, tender, and full of flavor — premium raw meat for your perfect recipes",
      'Price': 679,
      'AwailableQuantity': 25,
      'Img1': "images/Meat_P11_img1.jpeg",
      'Img2': "images/P11_img2.jpeg",
      'Img3': "images/P11_img3.jpeg",
      'Img4': "images/P11_img4.jpeg",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'CategoryId': 5,
      'ProductId': 11,
    },
    {
      'Name': "Cake",
      'Description': "Celebrate every moment with a soft, fluffy cake — sweetness that melts in your mouth",
      'Price': 800,
      'AwailableQuantity': 63,
      'Img1': "images/Cake_P12_img1.jpeg",
      'Img2': "images/P12_img2.jpeg",
      'Img3': "images/P12_img3.jpeg",
      'Img4': "images/P12_img4.jpeg",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'CategoryId': 6,
      'ProductId': 12,
    },
    {
      'Name': "Real Juice",
      'Description': "Refresh naturally with Real Juice — packed with fruity goodness in every sip",
      'Price': 179,
      'AwailableQuantity': 25,
      'Img1': "images/RealJuice_P13_img1.jpeg",
      'Img2': "images/P13_img2.jpeg",
      'Img3': "images/P13_img3.jpeg",
      'Img4': "images/P13_img4.jpeg",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'CategoryId': 7,
      'ProductId': 13,
    },
    {
      'Name': "Mccane Fries",
      'Description': "Crispy outside, soft inside — McCain brings you the perfect bite every time",
      'Price': 260,
      'AwailableQuantity': 63,
      'Img1': "images/Maccain_P14_img1.jpeg",
      'Img2': "images/P14_img2.jpeg",
      'Img3': "images/P14_img3.jpeg",
      'Img4': "images/P14_img4.jpeg",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'CategoryId': 3,
      'ProductId': 14,
    },
    {
      'Name': "Potato",
      'Description': "Farm-fresh potatoes — wholesome, versatile, and perfect for every dish",
      'Price': 35,
      'AwailableQuantity': 34,
      'Img1': "images/Aloo_P15_img1.jpeg",
      'Img2': "images/P15_img2.jpeg",
      'Img3': "images/P15_img3.jpeg",
      'Img4': "images/P15_img4.jpeg",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'CategoryId': 4,
      'ProductId': 15,
    },
    {
      'Name': "Onion",
      'Description': "Fresh, flavorful onions — the secret to adding taste and aroma to every meal",
      'Price': 45,
      'AwailableQuantity': 23,
      'Img1': "images/Onion_P16_img1.jpeg",
      'Img2': "images/P16_img2.jpeg",
      'Img3': "images/P16_img3.jpeg",
      'Img4': "images/P16_img4.jpeg",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'CategoryId': 4,
      'ProductId': 16,
    },
    {
      'Name': "Tomato",
      'Description': "Juicy, ripe tomatoes — bursting with freshness for your perfect recipes",
      'Price': 42,
      'AwailableQuantity': 83,
      'Img1': "images/Tomato_P17_img1.jpeg",
      'Img2': "images/P17_img2.jpeg",
      'Img3': "images/P17_img3.jpeg",
      'Img4': "images/P17_img4.jpeg",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'CategoryId': 4,
      'ProductId': 17,
    },
    {
      'Name': "Amul Paneer",
      'Description': "Amul Paneer — soft, creamy, and packed with protein for deliciously healthy meals",
      'Price': 188,
      'AwailableQuantity': 45,
      'Img1': "images/AmulPaneer_P18_img1.jpeg",
      'Img2': "images/P18_img2.jpeg",
      'Img3': "images/P18_img3.jpeg",
      'Img4': "images/P18_img4.jpeg",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'CategoryId': 1,
      'ProductId': 18,
    },
    {
      'Name': "Egg Tray",
      'Description': "Farm-fresh eggs — nutritious, versatile, and perfect for every meal",
      'Price': 279,
      'AwailableQuantity': 25,
      'Img1': "images/Egg_P19_img1.jpeg",
      'Img2': "images/P19_img2.jpeg",
      'Img3': "images/P19_img3.jpeg",
      'Img4': "images/P19_img4.jpeg",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'CategoryId': 2,
      'ProductId': 19,
    },
    {
      'Name': "Bread",
      'Description': "Soft, fresh bread — the perfect start to your day, every day",
      'Price': 20,
      'AwailableQuantity': 63,
      'Img1': "images/AmulBread_P20_img1.jpeg",
      'Img2': "images/P20_img2.jpeg",
      'Img3': "images/P20_img3.jpeg",
      'Img4': "images/P20_img4.jpeg",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'CategoryId': 1,
      'ProductId': 20,
    },

  ];


}
