import { Injectable } from '@angular/core';
import { ItemsClass } from './Classes/ItemClass';

@Injectable({
  providedIn: 'root'
})
export class ItemsListService {

  constructor() { }
  ProductsList: ItemsClass[] = [
    {
      'Name': "Spicy Noodles ",
      'Description': "Delicious, quick-cook noodles made from premium ingredients—perfect for satisfying cravings anytime, anywhere.",
      'Price': 20,
      'AwailableQuantity': 34,
      'Img1': "images/P1.png",
      'Img2': "",
      'Img3': "",
      'Img4': "",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'ProductTypeId': 0,
      'ProductId': 1,
    },
    {
      'Name': "Fresh Vegetables",
      'Description': "Crisp, farm-fresh vegetables packed with nutrients—perfect for healthy meals and vibrant, natural flavors.",
      'Price': 295,
      'AwailableQuantity': 23,
      'Img1': "images/P2.png",
      'Img2': "",
      'Img3': "",
      'Img4': "",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'ProductTypeId': 0,
      'ProductId': 2,
    },
     {
      'Name': "Baked Fresh Bread",
      'Description': "Soft, golden, and oven-fresh bread baked daily for rich flavor and irresistible homemade goodness.",
      'Price': 56,
      'AwailableQuantity': 83,
      'Img1': "images/P3.png",
      'Img2': "",
      'Img3': "",
      'Img4': "",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'ProductTypeId': 0,
      'ProductId': 3,
    },
     {
      'Name': "Burger Bun From fresh Oven",
      'Description': "Soft, fluffy burger buns with a light crust—perfect for holding your favorite fillings and flavors.",
      'Price': 125,
      'AwailableQuantity': 45,
      'Img1': "images/P4.png",
      'Img2': "",
      'Img3': "",
      'Img4': "",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'ProductTypeId': 0,
      'ProductId': 4,
    },
     {
      'Name': "Large Raw Shrimp",
      'Description': "Premium large raw shrimp, peeled and deveined—perfect for grilling, sautéing, or seafood recipes.",
      'Price': 499,
      'AwailableQuantity': 25,
      'Img1': "images/P5.png",
      'Img2': "",
      'Img3': "",
      'Img4': "",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'ProductTypeId': 0,
      'ProductId': 5,
    },
     {
      'Name': "Salmon Fillet",
      'Description': "Fresh, premium-quality salmon fillet—rich in omega-3s, perfect for grilling, baking, or sushi.",
      'Price': 349,
      'AwailableQuantity': 63,
      'Img1': "images/P6.png",
      'Img2': "",
      'Img3': "",
      'Img4': "",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'ProductTypeId': 0,
      'ProductId': 6,
    },
      {
      'Name': "Spicy Noodles ",
      'Description': "Delicious, quick-cook noodles made from premium ingredients—perfect for satisfying cravings anytime, anywhere.",
      'Price': 20,
      'AwailableQuantity': 34,
      'Img1': "images/P1.png",
      'Img2': "",
      'Img3': "",
      'Img4': "",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'ProductTypeId': 0,
      'ProductId': 1,
    },
    {
      'Name': "Fresh Vegetables",
      'Description': "Crisp, farm-fresh vegetables packed with nutrients—perfect for healthy meals and vibrant, natural flavors.",
      'Price': 295,
      'AwailableQuantity': 23,
      'Img1': "images/P2.png",
      'Img2': "",
      'Img3': "",
      'Img4': "",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'ProductTypeId': 0,
      'ProductId': 2,
    },
     {
      'Name': "Baked Fresh Bread",
      'Description': "Soft, golden, and oven-fresh bread baked daily for rich flavor and irresistible homemade goodness.",
      'Price': 56,
      'AwailableQuantity': 83,
      'Img1': "images/P3.png",
      'Img2': "",
      'Img3': "",
      'Img4': "",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'ProductTypeId': 0,
      'ProductId': 3,
    },
     {
      'Name': "Burger Bun From fresh Oven",
      'Description': "Soft, fluffy burger buns with a light crust—perfect for holding your favorite fillings and flavors.",
      'Price': 125,
      'AwailableQuantity': 45,
      'Img1': "images/P4.png",
      'Img2': "",
      'Img3': "",
      'Img4': "",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'ProductTypeId': 0,
      'ProductId': 4,
    },
     {
      'Name': "Large Raw Shrimp",
      'Description': "Premium large raw shrimp, peeled and deveined—perfect for grilling, sautéing, or seafood recipes.",
      'Price': 499,
      'AwailableQuantity': 25,
      'Img1': "images/P5.png",
      'Img2': "",
      'Img3': "",
      'Img4': "",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'ProductTypeId': 0,
      'ProductId': 5,
    },
     {
      'Name': "Salmon Fillet",
      'Description': "Fresh, premium-quality salmon fillet—rich in omega-3s, perfect for grilling, baking, or sushi.",
      'Price': 349,
      'AwailableQuantity': 63,
      'Img1': "images/P6.png",
      'Img2': "",
      'Img3': "",
      'Img4': "",
      'IsAdded': false,
      'QuantityAddedToCart': 0,
      'isWishlisted': false,
      'ProductTypeId': 0,
      'ProductId': 6,
    },
  ];
}
